import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillInstagram, AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
import Profilepic from "../public/parachute.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sander Olsen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 ">
        <section className=" bg-white-300 min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className=" text-2xl font-Gemunu">Sander's Portfolio</h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill className=" cursor-pointer text-xl" />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-slate-600 to-teal-500 text-white px-4 py-2 rounded-md ml-4"
                  href="#"
                >
                  Projects
                </a>
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-slate-600 to-teal-500 text-white px-4 py-2 rounded-md ml-4"
                  href="#"
                >
                  Contact
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium">
              Sander Lindberg Olsen
            </h2>
            <h3 className="text-2xl py-2">Front-end Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-900">
              Developer working for Posten
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-20 py-3 text-gray-600">
            <AiFillGithub />
            <AiFillInstagram />
            <AiFillLinkedin />
          </div>
          <div className=" relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={Profilepic} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3>Services</h3>
          </div>
        </section>
      </main>
    </div>
  );
}
